### ISSUE TITLE
Creating nested resource POST's to wrong URL

### ISSUE THREAD

**Issue by danielstocks** [remi/her#224]
I try this (as per the documentation)

``` ruby
class User
  include Her::Model
  has_many :comments
  has_one :role
  belongs_to :organization
end

class Comment
  include Her::Model
end
```

When I run this code in the Rails console:

``` ruby
user = User.find(1)
user.comments.create()
```

The POST request is made to **/comments** and not **/user/1/comments.**

The documentation clearly states that the POST request should be done to /user/1/comments. Did I do something wrong here?

**Comment by araslanov-e** [comment]
+1 (merge please)

**Comment by nosretep** [comment]
Is this still a known/unsolved issue?
