### ISSUE TITLE
I would like to have find_by! in order to raise an exception instead of a nil

### ISSUE THREAD

**Issue by amalagaura** [remi/her#532]
Is there interest to accept a PR for this? Is it as simple as adding `find_by!` which uses `find_by` and raises a Her::Model::RecordNotFound exception?

**Comment by zacharywelch** [comment]
Hi @amalagaura, agree that would be the rational solution and would love to see this, unfortunately there's a deeper issue with how the gem handles 4xx errors that would make it risky. For more info and workarounds see #334. Going to close this as a duplicate for now. Thanks!
